coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  # test utilities
  - "**/mock.*"
  # binary entry point
  - "**/main.rs"
