//! Memory domain types and actor sub-system for ClawChorus.
//!
//! Defines the core memory representations: [`RawMemory`], [`SynthesizedMemory`],
//! [`MemoryEntry`], and the actor-based Memory Manager sub-system.

use chrono::Utc;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

pub mod chunking;
pub mod config;
pub mod error;
pub mod file_op;
pub mod index;
pub mod messages;
mod path;
pub mod search_op;
pub mod storage;
pub mod synthesizer;

mod manager;
pub use manager::MemoryManager;

/// The type of a memory file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryType {
    /// A daily note uploaded from an agent (`memory/*.md` in openclaw).
    DailyNote,
    /// A snapshot to the long-term memory (`MEMORY.md` in openclaw).
    LongTerm,
}

/// The origin of a memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryOrigin {
    /// Pushed directly from an agent.
    Raw,
    /// Generated by ClawChorus to resolve conflicts.
    Synthesized,
}

/// A raw memory uploaded from a ClawChorus agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RawMemory {
    pub id: Uuid,
    pub memory_type: MemoryType,
    /// The username associated with the ClawChorus agent that uploaded
    /// this memory.
    pub username: String,
    /// The agent id of the ClawChorus agent that uploaded this memory.
    pub agent_id: Uuid,
    /// Unix epoch timestamp in seconds.
    pub timestamp: i64,
    /// The full file content (plain Markdown, no frontmatter).
    pub content: String,
}

impl RawMemory {
    pub fn new(memory_type: MemoryType, username: String, agent_id: Uuid, content: String) -> Self {
        Self {
            id: Uuid::new_v4(),
            memory_type,
            username,
            agent_id,
            timestamp: Utc::now().timestamp(),
            content,
        }
    }
}

/// A synthesized memory produced by ClawChorus to resolve conflicts
/// between raw memories.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SynthesizedMemory {
    pub id: Uuid,
    pub memory_type: MemoryType,
    /// Owner username. `None` for org-wide (`_unified`) syntheses.
    pub username: Option<String>,
    /// UUIDs of the source memories that were merged.
    pub sources: Vec<Uuid>,
    /// Unix epoch timestamp in seconds.
    pub timestamp: i64,
    /// The synthesized content (plain Markdown, no frontmatter).
    pub content: String,
}

impl SynthesizedMemory {
    pub fn new(
        memory_type: MemoryType,
        username: Option<String>,
        sources: Vec<Uuid>,
        content: String,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            memory_type,
            username,
            sources,
            timestamp: Utc::now().timestamp(),
            content,
        }
    }
}

/// A single memory entry — either a [`RawMemory`] or a [`SynthesizedMemory`].
/// The `MemoryManager` always returns fully hydrated entries.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum MemoryEntry {
    Raw(RawMemory),
    Synthesized(SynthesizedMemory),
}

impl MemoryEntry {
    pub fn id(&self) -> Uuid {
        match self {
            MemoryEntry::Raw(m) => m.id,
            MemoryEntry::Synthesized(m) => m.id,
        }
    }

    pub fn content(&self) -> &str {
        match self {
            MemoryEntry::Raw(m) => &m.content,
            MemoryEntry::Synthesized(m) => &m.content,
        }
    }

    pub fn origin(&self) -> MemoryOrigin {
        match self {
            MemoryEntry::Raw(_) => MemoryOrigin::Raw,
            MemoryEntry::Synthesized(_) => MemoryOrigin::Synthesized,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn raw_memory_new_sets_defaults() {
        let agent_id = Uuid::new_v4();
        let raw = RawMemory::new(
            MemoryType::DailyNote,
            "bob@example.com".to_string(),
            agent_id,
            "some content".to_string(),
        );

        assert_eq!(raw.memory_type, MemoryType::DailyNote);
        assert_eq!(raw.username, "bob@example.com");
        assert_eq!(raw.agent_id, agent_id);
        assert_eq!(raw.content, "some content");
        assert!(raw.timestamp > 0);
        assert_ne!(raw.id, Uuid::default());
    }

    #[test]
    fn synthesized_memory_new_sets_defaults() {
        let source = Uuid::new_v4();
        let synth = SynthesizedMemory::new(
            MemoryType::LongTerm,
            Some("alice@example.com".to_string()),
            vec![source],
            "merged content".to_string(),
        );

        assert_eq!(synth.memory_type, MemoryType::LongTerm);
        assert_eq!(synth.username.as_deref(), Some("alice@example.com"));
        assert_eq!(synth.sources, vec![source]);
        assert_eq!(synth.content, "merged content");
        assert!(synth.timestamp > 0);
        assert_ne!(synth.id, Uuid::default());
    }

    #[test]
    fn synthesized_memory_org_wide_has_no_username() {
        let synth = SynthesizedMemory::new(
            MemoryType::DailyNote,
            None,
            vec![Uuid::new_v4()],
            "org-wide synthesis".to_string(),
        );

        assert!(synth.username.is_none());
    }

    #[test]
    fn memory_type_serde_roundtrip() {
        let json = serde_json::to_string(&MemoryType::DailyNote).unwrap();
        assert_eq!(json, "\"daily_note\"");
        let back: MemoryType = serde_json::from_str(&json).unwrap();
        assert_eq!(back, MemoryType::DailyNote);

        let json = serde_json::to_string(&MemoryType::LongTerm).unwrap();
        assert_eq!(json, "\"long_term\"");
    }

    #[test]
    fn memory_origin_serde_roundtrip() {
        let json = serde_json::to_string(&MemoryOrigin::Raw).unwrap();
        assert_eq!(json, "\"raw\"");
        let back: MemoryOrigin = serde_json::from_str(&json).unwrap();
        assert_eq!(back, MemoryOrigin::Raw);

        let json = serde_json::to_string(&MemoryOrigin::Synthesized).unwrap();
        assert_eq!(json, "\"synthesized\"");
    }

    #[test]
    fn memory_entry_delegates_to_inner() {
        let raw = RawMemory::new(
            MemoryType::DailyNote,
            "alice".to_string(),
            Uuid::new_v4(),
            "hello".to_string(),
        );
        let entry = MemoryEntry::Raw(raw.clone());

        assert_eq!(entry.id(), raw.id);
        assert_eq!(entry.content(), "hello");
        assert_eq!(entry.origin(), MemoryOrigin::Raw);

        let synth = SynthesizedMemory::new(MemoryType::LongTerm, None, vec![], "world".to_string());
        let entry = MemoryEntry::Synthesized(synth.clone());

        assert_eq!(entry.id(), synth.id);
        assert_eq!(entry.content(), "world");
        assert_eq!(entry.origin(), MemoryOrigin::Synthesized);
    }
}
